#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 10-coturn
PROCESS_NAME="coturn-cert-reload"

check_container_initialized
check_service_initialized init
liftoff

while inotifywait -q -e create,delete,modify,attrib ${TLS_CERT_FILE} ${TLS_KEY_FILE}
 do
  print_info "Reloading Coturn to a detected certificate change"
  pkill -1 coturn
  exit 0
done
