version: '2.4'
services:
  
  coturn-app:
    image: tiredofit/coturn:latest
    container_name: coturn-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.coturn.rule=Host(`turn.example.com`)
    volumes:
      #- /var/local/data/traefik/certs/dump/turn.example.com:/certs
      - ./data:/data
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=coturn-app

      - SETUP_MODE=bbb

      - SECRET=supersecretpassword
      - REALM=turnserver.local
    
      - TLS_CERT=cert.pem
      - TLS_KEY=key.pem
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external:true
  services:
    external: true

