#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service both 10-coturn
PROCESS_NAME="coturn"

check_container_initialized
check_service_initialized init

liftoff
print_info "Starting coturn ${COTURN_VERSION}"
exec /usr/bin/turnserver -c ${CONFIG_PATH}${CONFIG_FILE}
